name: MambaQuant_train_x4
model_type: MambaQuantModel
scale: 4
num_gpu: 1
manual_seed: 3407
gpu: 0
bit: 4
prune_keep_frac: 0.6
cali_data: keydata/cali_data_x4.pth
quant:
  hook_per_layer: True
  hook_per_block: False
  qkv_separation: True
# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: datasets/DF2K/HR
    dataroot_lq: datasets/DF2K/LR_bicubic/X4
    filename_tmpl: "{}x4"
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: True
    use_rot: True
    # data loader
    use_shuffle: True
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: cpu
    pin_memory: True
    num_prefetch_queue: 16
  val_0:
    task: SR
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Set5/HR
    dataroot_lq: datasets/benchmark/Set5/LR_bicubic/X4
    filename_tmpl: "{}x4"
    io_backend:
      type: disk
# network structures
# MambaIRv2 light
network_Q:
  type: MambaIRv2Light
  upscale: 4
  img_size: 64
  window_size: 16
  img_range: 1.
  # MambaIRv2 light parameters
  embed_dim: 48
  d_state: 8
  depths: [5, 5, 5, 5]
  num_heads: [4, 4, 4, 4]
  inner_rank: 32
  num_tokens: 64
  convffn_kernel_size: 5
  mlp_ratio: 1.
  upsampler: pixelshuffledirect
# paths
pathFP:
  #pretrain_network_FP: experiments/pretrained_models/MambaIRv2/MambaIRv2_light_x2.pth
  pretrain_network_FP: experiments/pretrained_models/Mamba/mambairv2_lightSR_x4.pth
  strict_load_FP: true
path:
  pretrain_network_Q: ~
  strict_load_Q: ~
# training settings
train:
  optim_bound:
    type: Adam
    lr: !!float 1e-2
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_bit:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]
  scheduler:
    type: MultiStepLR
    milestones: [10000]
  total_iter: 4000
  warmup_iter: -1 # no warm up
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  feature_loss:
    type: MSELoss
    loss_weight: 5
    reduction: mean
# validation settings
val:
  val_freq: !!float 100
  save_img: False
  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: True
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 2
      test_y_channel: True
# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 100
  use_tb_logger: True
  # wandb:
  #   project: ptq
  #   resume_id: ~
# dist training settings
dist_params:
  backend: nccl
  port: 29500